kotlin.code.style=official

org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.tooling.parallel=true

# TODO: https://github.com/LawnchairLauncher/lawnchair/pull/6277
android.newDsl=false
