name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build APK
        run: ./gradlew assembleLawnWithQuickstepPlayDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: debug-apk
          path: build/outputs/apk/**/*.apk

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew spotlessCheck

  # Status check required by branch protection rules.
  final-status:
    needs:
      - build-debug-apk
      - check-style
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
          echo "All required jobs completed successfully."
